name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: law-pdflatex.tex
      - name: Compile Instructions
        uses: xu-cheng/latex-action@v2
        with:
          root_file: sample-bookchapter.tex
          working_directory: instructions
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            law-pdflatex.pdf
            instructions/sample-bookchapter.pdf
